# Generated by Django 5.0 on 2023-12-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addr',
            name='address',
            field=models.CharField(max_length=200, verbose_name='详细地址'),
        ),
    ]
