# Generated by Django 5.0 on 2023-12-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_addr_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='level',
            field=models.CharField(max_length=20, null=True, verbose_name='区域等级'),
        ),
        migrations.AlterField(
            model_name='area',
            name='pid',
            field=models.IntegerField(default=True, verbose_name='上级id'),
        ),
    ]
