# Generated by Django 5.0 on 2023-12-24 07:33

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(default='', max_length=200, verbose_name='标题')),
                ('desc', models.CharField(max_length=200, verbose_name='商品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='', verbose_name='封面图链接')),
                ('stock', models.IntegerField(blank=True, default=1, verbose_name='库存')),
                ('sales', models.IntegerField(blank=True, default=1, verbose_name='销量')),
                ('is_on', models.BooleanField(blank=True, default=False, verbose_name='是否上架')),
                ('recommend', models.BooleanField(blank=True, default=False, verbose_name='是否推荐')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(default='', max_length=200, verbose_name='轮播图名称')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='轮播图链接')),
                ('status', models.BooleanField(default=False, verbose_name='是否启用')),
                ('seq', models.IntegerField(blank=True, default=1, verbose_name='顺序')),
            ],
            options={
                'verbose_name': '首页商品轮播图',
                'verbose_name_plural': '首页商品轮播图',
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='GoodsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('image', models.ImageField(max_length=20, upload_to='', verbose_name='图片')),
                ('status', models.BooleanField(default=False, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '商品分类表',
                'db_table': 'goods_group',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('producer', models.CharField(max_length=200, verbose_name='厂商')),
                ('norms', models.CharField(max_length=200, verbose_name='规格')),
                ('detail', ckeditor.fields.RichTextField(blank=True, verbose_name='商品详情')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品详情表',
                'verbose_name_plural': '商品详情表',
                'db_table': 'detail',
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, help_text='用户ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
                ('goods', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品ID')),
            ],
            options={
                'verbose_name': '收藏商品',
                'verbose_name_plural': '收藏商品',
                'db_table': 'collect',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodsgroup', verbose_name='分类'),
        ),
    ]
