# Generated by Django 5.0 on 2023-12-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'verbose_name': '商品详情', 'verbose_name_plural': '商品详情'},
        ),
    ]
