# Generated by Django 5.0 on 2023-12-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_detail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片'),
        ),
    ]
