# Generated by Django 5.0 on 2023-12-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_goodsgroup_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsgroup',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='goodsgroup',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='goodsgroup',
            name='update_time',
        ),
    ]
